// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesAPI.Data;

#nullable disable

namespace MoviesAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231127142451_addUsertbl")]
    partial class addUsertbl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesAPI.Models.Movies", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Country = "India",
                            Director = "Unknown",
                            Genre = "Patriotic",
                            Industry = "Unknown",
                            Name = "Chanakya",
                            Synopsis = "Lorem Ipsum"
                        },
                        new
                        {
                            ID = 2,
                            Country = "India",
                            Director = "Unknown",
                            Genre = "Patriotic",
                            Industry = "Unknown",
                            Name = "Chanakya",
                            Synopsis = "Lorem Ipsum"
                        },
                        new
                        {
                            ID = 3,
                            Country = "India",
                            Director = "Unknown",
                            Genre = "Patriotic",
                            Industry = "Unknown",
                            Name = "Chanakya",
                            Synopsis = "Lorem Ipsum"
                        },
                        new
                        {
                            ID = 4,
                            Country = "India",
                            Director = "Unknown",
                            Genre = "Patriotic",
                            Industry = "Unknown",
                            Name = "Chanakya",
                            Synopsis = "Lorem Ipsum"
                        },
                        new
                        {
                            ID = 5,
                            Country = "India",
                            Director = "Unknown",
                            Genre = "Patriotic",
                            Industry = "Unknown",
                            Name = "Chanakya",
                            Synopsis = "Lorem Ipsum"
                        });
                });

            modelBuilder.Entity("MoviesAPI.Models.User", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
